### ISSUE TITLE
关于templatetag问题

### ISSUE THREAD

**Issue by Njsc** [zmrenwu/django-blog-tutorial#13]
我是把作者的templatetag的文件夹直接拷贝到自己的项目下，但是在html中{% load paginate_tags %}是没有提示而且网页报错django.template.exceptions.TemplateSyntaxError: 'paginate_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
...

**Comment by zmrenwu** [comment]
贴一下paginate_tags.py的代码
