### ISSUE TITLE
blog_project/urls.py 中这样改是好还是不好呢

### ISSUE THREAD

**Issue by JFluo2011** [zmrenwu/django-blog-tutorial#20]
第一种方式：
url(r'', include('blog.urls', namespace='blog', app_name='blog')),
第二种方式：
url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),

请问上面哪种方式更好呢？

**Comment by zmrenwu** [comment]
@JFluo2011 都是一样的，为了测试方便可以使用第一种，这样直接访问根url就可以显示主页。
