### ISSUE TITLE
一些风格和小技巧建议

### ISSUE THREAD

**Issue by WPH95** [zmrenwu/django-blog-tutorial#28]
1. rename blog_project => config
2. add import local_settings

http://stackoverflow.com/questions/4909958/django-local-settings

**Comment by zmrenwu** [comment]
remane 会产生什么相关联的影响么？比如导致某些依赖的路径不可用了。

**Comment by sunblognuke** [comment]
建议修改，如此命名明确清晰 :)

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
