### ISSUE TITLE
能否给 templates 文件写点文档，看的有点懵

### ISSUE THREAD

**Issue by strugglingyouth** [zmrenwu/django-blog-tutorial#32]
还有就是有没有关于基于类的视图的相关说明，django 新手有些看的不是很明白

**Comment by zmrenwu** [comment]
好的，这一块后面补充几篇文章。template是html不懂还是那些模板标签不懂呢？


Sent from Mail Master
在2016年05月31日 17:05，struggling 写道:

还有就是有没有关于基于类的视图的相关说明，django 新手有些看的不是很明白

**Comment by strugglingyouth** [comment]
布局大概说明一下  模板中使用变量的地方也稍微说明一下  多谢

**Comment by zmrenwu** [comment]
好的👌🏻，后续我写几篇补充教程。你先尝试着理解一下


Sent from Mail Master
在2016年05月31日 17:23，struggling 写道:

布局大概说明一下 模板中使用变量的地方也稍微说明一下 多谢

**Comment by Superb-x** [comment]
现在大多数项目都是前后端分离了，前端的模板引擎也很强大，比如angular、Vue、React。稍微去看下前端的东西对模板这里理解会快点。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
