### ISSUE TITLE
后面会不会对后端进行完善，比如，使用缓存服务器

### ISSUE THREAD

**Issue by strugglingyouth** [zmrenwu/django-blog-tutorial#33]

**Comment by upczww** [comment]
会的，现在只是初步实现功能，以后会优化性能的。

**Comment by zmrenwu** [comment]
如果服务器有需要的话！

**Comment by bdbai** [comment]
先把功能完成，等上了规模以后再考虑性能问题。
话说楼主是 IPN 听友吗？

**Comment by WPH95** [comment]
缓存服务器是个很范的概念。
后端可以考虑在 db 与 server 之间加一层 cache
前端也可以考虑加 cdn

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
