### ISSUE TITLE
建议每一周教程添加一个tag

### ISSUE THREAD

**Issue by qcsky** [zmrenwu/django-blog-tutorial#35]
建议每一周的教程添加一个tag，大家可以根据自己的进度来找相关的章节的代码。
类似下面这样子的。
![Tag](http://i.imgur.com/ymsdGBO.png)

**Comment by zmrenwu** [comment]
好的，谢谢建议，从这周开始吧，前面的提交比较难找了。

**Comment by WPH95** [comment]
可以这周开始

1. 维护一个 step/ 前缀的分支。
2. 维护一个 week/ 前缀的tag，发布稳定版。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
