### ISSUE TITLE
CI 与 Demo

### ISSUE THREAD

**Issue by WPH95** [zmrenwu/django-blog-tutorial#36]
1. CI 是指 Continuous integration 。当项目测试跟上之后，所有 branch 需要通过 ci 后方可 merge
2. Demo ，需要服务器运行当前版本的 blog。

**Comment by WPH95** [comment]
CI 的可选列表

1. Travis CI
2. Circle CI

Demo 可选列表

1. Daocloud （配合 PR 自动更新代码）
2. Github Page （考虑到我们不是静态页面，并不太建议此项）

**Comment by bdbai** [comment]
CI 也用 DaoCloud 的如何？
我自己搭了一个演示： http://bdbai-djbg.daoapp.io/

**Comment by WPH95** [comment]
DaoCloud 不提供类似 travis ci ，jenkins 这种集成到github 里的功能。
我想要的效果是这样的 
![qq20160607-0 2x](https://cloud.githubusercontent.com/assets/2732352/15830331/3682c87a-2c4a-11e6-8feb-21f679cda595.png)

https://github.com/docker/docker/pull/23312

**Comment by bdbai** [comment]
Travis CI 用的人多一点。
我们这种项目抽象程度并不高，测试怎么写比较好？
底下的 Issue 是什么😂 @WPH95

**Comment by zmrenwu** [comment]
同问，测试方面该测什么？是否有相关的教程或者 demo 以供参考？

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
