### ISSUE TITLE
在model添加tag字段后，重新生成数据后，数据库被清空了，以前的测试文章全不见了

### ISSUE THREAD

**Issue by strugglingyouth** [zmrenwu/django-blog-tutorial#45]
![Uploading QQ图片20160624162025.png…]()

**Comment by strugglingyouth** [comment]
![qq 20160624162025](https://cloud.githubusercontent.com/assets/10249666/16332349/0f4498e2-3a28-11e6-9f9c-928ae909bd13.png)

**Comment by zmrenwu** [comment]
好像还没遇到过这种情况，数据库文件有加入git管理么

**Comment by bdbai** [comment]
理论上 migrate 不会影响到原有数据的，是不是操作 Git 的时候顺带把数据库文件弄丢了？可以提供一下修改后的代码么？

**Comment by strugglingyouth** [comment]
@bdbai  代码就是按教程修改的， 数据库文件加入git管理了

**Comment by strugglingyouth** [comment]
求问  如何能恢复数据

**Comment by zmrenwu** [comment]
那就回退到没删除的版本吧，然后重新再试一下。

**Comment by bdbai** [comment]
```bash
git log # 找到有数据库的一次 commit hash
git reset <commit hash> # 不带尖括号，只要前六位
```
另外我觉得`按照教程改代码` 与 `pull 代码保持同步`会有冲突， @zmrenwu 你怎么看？

**Comment by zmrenwu** [comment]
我是尽量边写代码边写教程，可能有地方遗漏。如果有冲突的地方希望指出来，我改一下。


Sent from Mail Master
在2016年06月25日 17:53，bdbai 写道:
git log # 找到有数据库的一次 commit hash
git reset <commit hash># 不带尖括号，只要前六位

另外我觉得按照教程改代码 与 pull 代码保持同步会有冲突， @zmrenwu 你怎么看？

**Comment by bdbai** [comment]
@zmrenwu 换种说法，有些人想照着教程 DIY，下次他 pull 代码的时候就悲剧了...

**Comment by zmrenwu** [comment]
@bdbai 这没办法吧。解决一下冲突咯。

**Comment by strugglingyouth** [comment]
@zmrenwu   git 能管理 mysql 文件吗  ，我将mysql 文件加入 git 管理，但是进行版本回退后，django中的文章并没有删除

**Comment by bdbai** [comment]
@strugglingyouth MySQL 数据库的数据文件是存在别处的，在配置里面设定。你说的 MySQL 文件是指？

另外版本回退不一定会影响工作区，除非 `git reset --hard` 这样。

**Comment by strugglingyouth** [comment]
@bdbai  就是下面这个，用 git 管理不了
![mysql-test](https://cloud.githubusercontent.com/assets/10249666/16683043/5ee656c0-4530-11e6-8c63-cab50ff6e008.png)

**Comment by bdbai** [comment]
@strugglingyouth 数据库不应该让 Git 管😂。我们提倡的是代码和数据分开，数据只要存在部署的服务器上即可。
另外这里面应该是一大堆二进制文件，并不是 Git 所擅长管理的。

**Comment by strugglingyouth** [comment]
我看上面 @zmrenwu  说把数据库文件加入git ，难道不是加这个

**Comment by bdbai** [comment]
我觉得他这是句疑问句。

**Comment by strugglingyouth** [comment]
恩  好吧

**Comment by zmrenwu** [comment]
sqlite3的话加入git管理是没问题的。但是mysql的数据库文件似乎不在.git目录下，你应该不会加入git，所以我想你的文件应该还在的，找到mysql对应的表所在的目录，用sql工具查看一下，看数据是否真的被清空了。理论上来说migrate不可能删除数据。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
