### ISSUE TITLE
views.IndexView.as_view()

### ISSUE THREAD

**Issue by fpk2014** [zmrenwu/django-blog-tutorial#5]
blog_object/urls.py中

urlpatterns = [

   url(r'^admin/', admin.site.urls),

```
url(r'^blog/', views.IndexView.as_view()),
```

]

views.IndexView.as_view()传递了哪些参数？看不大明白，哪位高手能解释下？

**Comment by zmrenwu** [comment]
@fpk2014 IndexView没有传递任何参数，只是从数据库获取文章列表并返回给前台而已。DetailView和CategoryView涉及到参数传递，请先参考下相关代码。如有不懂再发Issue

**Comment by fpk2014** [comment]
@ @
因为我输入了下面的命令：
>>> from django.views.generic.list import ListView
>>> help(ListView.as_view)
Help on method as_view in module django.views.generic.base:

as_view(cls, **initkwargs) method of __builtin__.type instance
    Main entry point for a request-response process.

返回的帮助提醒我有两个参数可以输入，所以比较迷惑。

**Comment by fuyunliu** [comment]
问一个问题，代码中的中文字符串前面都没有加u，还有首行没有`# -*- coding: utf-8 -*-`，想问什么情况下要使用，是因为python3才不需要吗？

**Comment by zmrenwu** [comment]
@fpk2014 cls参数是class的缩写，即传入的是类本身，实例本身用self，python的一种习惯。**initkwargs这个是用于接收参数的，不过也可以不传递参数。

**Comment by zmrenwu** [comment]
@fuyunliu 这似乎是python 3的好处之一，目前的实践来看不加编码声明好像没有遇到什么问题。

**Comment by fpk2014** [comment]
好的，谢谢大神。
