### ISSUE TITLE
请问数据库设计中那个摘要，好像没有实现

### ISSUE THREAD

**Issue by strugglingyouth** [zmrenwu/django-blog-tutorial#54]

**Comment by zmrenwu** [comment]
有的吧，abstract就是摘要

**Comment by strugglingyouth** [comment]
@zmrenwu   那个是要手动输入吗   我以为是代码生成

**Comment by zmrenwu** [comment]
@strugglingyouth model 的save方法里好像实现了自动摘要，摘取正文的前X个字符。

**Comment by jywu90** [comment]
@zmrenwu 有个问题，因为文章是markdown格式的，如果直接提取前X个字符，会有markdown的标记符，比如**， > 之类的

**Comment by zmrenwu** [comment]
嗯。，这个问题暂时没有考虑，因为也没想到优雅的解决方案。

**Comment by jywu90** [comment]
@zmrenwu 尝试用正则表达式解决了这个问题：
import re
    def save(self, *args, **kwargs):
        self.body = markdown2.markdown(self.body, extras=['fenced-code-blocks'], )
        self.body = re.sub(r'<.+?>', r'', self.body)  #删除html文件的所有tag
        self.abstract = self.abstract or self.body[:400]
        super(Article, self).save(*args, **kwargs)

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
