### ISSUE TITLE
页面跳转，公共的内容如何显示，比如右侧的标签？从blog列表跳转到blog详情页面，如果同样想显示右侧的标签页面，除了重新计算并添加上下文tag_list，还有其它方式吗？

### ISSUE THREAD

**Issue by apprentice1985** [zmrenwu/django-blog-tutorial#55]
页面跳转，公共的内容如何显示，比如右侧的标签？从blog列表跳转到blog详情页面，如果同样想显示右侧的标签页面，除了重新计算并添加上下文tag_list，还有其它方式吗？

IndexView 使用blog/index.html 显示文章列表，右侧显示标签。

```
                <div class="list-group">
                    {% for tag in tag_list %}
                        <a href="{% url 'blog:tag' tag.pk %}" class="list-group-item"><span
                                class="badge"></span>{{ tag.name }}</a>
                    {% endfor %}
                </div>
```

`kwargs['tag_list'] = Tag.objects.all().order_by('name')
`

点击任何一个blog，进入blog详情页面blog/detail.html，如果我要显示同样的标签，归档应该如何做？
只能添加同样的内容到上下文kwargs['tag_list']中嘛？

```
class ArticleDetailView(DetailView):
def get_context_data(self, **kwargs):
        kwargs['comment_list'] = self.object.blogcomment_set.all()
        kwargs['form'] = BlogCommentForm()
        **kwargs['tag_list'] = Tag.objects.all().order_by('name')**
        return super(ArticleDetailView, self).get_context_data(**kwargs)
```

**Comment by bdbai** [comment]
所谓“跳转”感觉好像页面之间是连续的。实际上，你每一个链接点下去，浏览器都会重新给服务器发请求，服务器组织好页面后一股脑传回，这样浏览器才能渲染整个页面。这体现了 HTTP 无状态的特性。
我们可以用 PJAX 或者纯 AJAX 来实现，但这样会改动很多代码，前后端都要动。

**Comment by zmrenwu** [comment]
@apprentice1985 可参考 django 文档关于 contex_processors 的介绍，或者百度应该能看到相关教程。目前我做的这个教程不够完善，因为目前科研任务有点重，考虑过段时间重做教程。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
