### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by fuyunliu** [zmrenwu/django-blog-tutorial#6]
建议settings.py加一行
`location = lambda x: os.path.join(BASE_DIR, x)`

**Comment by zmrenwu** [comment]
@fuyunliu 可否简单说明一下这一行的作用呢？

**Comment by fuyunliu** [comment]
settings.py 下面的路径可以统一用`location('filedir')`，没多高深，只是简洁而已。

**Comment by fuyunliu** [comment]
还有啊，能把依赖库requirements.txt也传到版本库吗？

**Comment by zmrenwu** [comment]
好的，明白了，那个马上加上。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
