### ISSUE TITLE
我目前在服务器发布方面有一些问题，请问你们是用什么来发布网站的呢

### ISSUE THREAD

**Issue by JasonLearning** [zmrenwu/django-blog-tutorial#65]

**Comment by zmrenwu** [comment]
我的 demo 是 nginx + gunicorn

**Comment by JasonLearning** [comment]
@zmrenwu 请问有推荐的教程吗，我目前服务器的系统是centos6，之前使用nginx与uwsgi部署的时候无法链接静态文件，并且监视的端口也有点问题

**Comment by bdbai** [comment]
collectstatic 执行了吗？
建议你换 Gunicorn 试一下。

**Comment by JasonLearning** [comment]
@bdbai 执行了的，前面改了一下好笑nginx直接不对了，您能帮我看下我的配置文件有问题吗，网上有各种版本的
    server {
        listen       8097;
        server_name  localhost;
        charset UTF-8;
        #charset koi8-r;

        #access_log  logs/host.access.log  main;
        location ~/static/ {
            alias /root/djangoBlog/jasonBlog/static;
            autoindex on;
        }
        location / {
            include uwsgi_params;
            uwsgi_pass 127.0.0.1:9099;
        }

**Comment by coldsummerday** [comment]
http://www.jianshu.com/p/b9d7e1f0e97b    血泪史 搭在apache 上

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
