### ISSUE TITLE
foreignKey默认值问题

### ISSUE THREAD

**Issue by feiaf** [zmrenwu/django-blog-tutorial#67]
我使用ForeignKey时候，系统提示我要选择一个默认值，如下所示：
You are trying to add a non-nullable field 'category' to myblog without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py

如果我选择1，设置成0，系统说没有这个值，我该怎么处理？

**Comment by houshengandt** [comment]
这个不是ForeignKey的问题吧。
如果你的'category'是CharField，试试 '0' 。

**Comment by zmrenwu** [comment]
当数据库已经有数据时，必须为新添加的列填充值，可以查一下你的数据库，找一个存在的 Category 的 id，选择1，输入该id即可

**Comment by glaresummer** [comment]
多谢了，我已经解决了 ，ForeignKey('category',null=True,blank=True)就不报错了。
