### ISSUE TITLE
想请问一下关于静态文件的问题

### ISSUE THREAD

**Issue by JasonLearning** [zmrenwu/django-blog-tutorial#68]
我这边的静态文件依旧读取不出来，目前查看网页上解析出来css的地址在http://138.128.197.124/static/blog/css/style.css
我的location部分这么写的
location /static/ {
             alias /root/djangoBlog/jasonBlog/static/;
        }
确认过所有的static文件都是在这个目录下面的，想请问下为何无法访问呢

**Comment by Superb-x** [comment]
应该就是路径的问题,要在setting.py里边设置下
`STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'client/dist/static'),
    os.path.join(BASE_DIR, 'static')
]`
https://docs.djangoproject.com/en/1.11/howto/static-files/   具体的可以看看这个文档

**Comment by MidiGeek** [comment]
同样的问题，我也是使用的nginx做的静态资源处理，/static/blog/下的资源可以正常访问，但是/static/admin/下的静态资源无法访问到，你需要把nginx配置下的/static/换成/static/blog/就可以了，同理admin的资源文件也是这样

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
