### ISSUE TITLE
在项目中用CKeditor怎么设置成简体中文？

### ISSUE THREAD

**Issue by feiaf** [zmrenwu/django-blog-tutorial#69]
blog后台编辑的时候，我引入一个CKeditor, 在config.js里面我已经将语言写成了简体中文language=‘zh-cn’，为什么后台编辑界面显示的是繁体？有什么办法改成简体中文？

**Comment by zmrenwu** [comment]
settings.py 文件有没把语言设置成 zh-Hans

**Comment by glaresummer** [comment]
zh-Hans已经设置了，但是还是不行

**Comment by zmrenwu** [comment]
那这应该是 CKeditor 的配置问题，参考一下他的文档。

**Comment by glaresummer** [comment]
我下载了一个，而且上面也没有pluign文件下也没有toolbar这个文件夹，一般应该下载那个版本？

**Comment by zmrenwu** [comment]
不好意思，我没有用过富文本编辑器，可以考虑使用这个项目：https://github.com/django-ckeditor/django-ckeditor，或者 https://github.com/timmyomahony/django-pagedown，pagedown 为文本编辑区域提供了一个 markdown 实时预览功能。

**Comment by FanQiePy** [comment]
我也遇见了这个问题，折腾了好久，最后是把setting文件中的LANGUAGE_CODE = 'ZH-hans'改成LANGUAGE_CODE = 'zh-hans'，心疼自己。

**Comment by feiaf** [comment]
因为这个问题，我都不用CKeditor了

**Comment by xhzxlqt** [comment]
可以这样处理：
将static/ckeditor/ckeditor/plugins/codesnippet/lang/zh.js
static/ckeditor/ckeditor/lang/zh.js
这两个文件用zh-cn.js替换，并将其中的zh-cn改为zh即可
