### ISSUE TITLE
为什么我的跑起来的博客里没有分页，看不到任何分页

### ISSUE THREAD

**Issue by shoneSolomon** [zmrenwu/django-blog-tutorial#70]

**Comment by zmrenwu** [comment]
可能文章数太少。可以在代码里设置一下每页的文章数，让它满足分页条件。

**Comment by shoneSolomon** [comment]
我建立了十几篇文章来测试，但是我发现分页模板没有，而且评论模块，你说的blog/form.py 根本没有啊，而且是在comments下面，而且blog/views.py 里面也没有CommentPostView这个，而是在comments里面，但是那些为什么又注释掉了，感觉有点混乱，按照你说的，很多就没法写了，没法按照教程写了。

**Comment by zmrenwu** [comment]
你使用的是 blog-tutorial 分支的代码么? 那里面的评论和分页都是可以的。教程的代码也是这个分支的代码。

**Comment by shoneSolomon** [comment]
恩 ，可能 我搞错了，git clone 的时候出错了，我再看看

**Comment by mugbya** [comment]
亲测可用，但要用就用整套，不然就会向我一样分页失败.... 我还是调试了好久搞定了...

> ps:   建议 owner  将  jquery.js  跟  bootstrap.min.js 的加载顺利换下位置... 原因你能搜到的

谢谢 ^_^
