### ISSUE TITLE
在配置uwsgi时，配置文件的module参数应该如何填写呢？

### ISSUE THREAD

**Issue by seniorcandy** [zmrenwu/django-blog-tutorial#71]
Django 文档里的意思好像是  有wsgi.py文件的文件夹名字 + '.wsgi'
试了好几种都出现了Import Error: No module named 'weblog/config'

**Comment by zmrenwu** [comment]
这可能是 config 不在 python 路径中，如果还是有问题的话尝试把 'weblog/config' 改成 apps/weblog/config
