### ISSUE TITLE
如何给摘要设置默认值

### ISSUE THREAD

**Issue by kgf0ry** [zmrenwu/django-blog-tutorial#75]
关于模型中的 summary 我想在文章写好后，让摘要默认为文章的前５４个字符。该如何实现。?
　我自己 Gｏｏｇｌｅ 后，感觉 getattr( ) 函数可以用在这。但又没思路。

**Comment by zmrenwu** [comment]
可以这样，self.summary=self.body[:54]，不过这样截取有可能会截断 markdown 语句。更好的方法是在模板引擎中使用 {{ article.body | truncate_html:54 }}。更加高级的方法参考 django-model-utils 的 SplitField 使用方法，将 TextField 改为 SplitField。

**Comment by zmrenwu** [comment]
http://zmrenwu.com/post/32/
