### ISSUE TITLE
project 的url和application的url问题

### ISSUE THREAD

**Issue by crazy-canux** [zmrenwu/django-blog-tutorial#77]
project：
url(r'^blog/', include('blog.urls')),
application：
url(r'^$', views.IndexView.as_view(), name='blog')

project
url(r'', include('blog.urls', namespace='blog', app_name='blog'))
application:
url(r'^blog/$', views.IndexView.as_view(), name='index')

What's the different?

**Comment by zmrenwu** [comment]
see https://docs.djangoproject.com/en/1.10/intro/tutorial03/ https://docs.djangoproject.com/en/1.10/topics/http/urls/
