### ISSUE TITLE
无法加载article的视图怎么回事？

### ISSUE THREAD

**Issue by xiaomintongxue** [zmrenwu/django-blog-tutorial#78]
按照url输入http://127.0.0.1:8000/article/1测试，提示You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.按照提示更改之后为什么还是无法加载detail视图？是需要先去后台建立文章才能有吗？

**Comment by zmrenwu** [comment]
嗯，要先到后台发布一些文章。

**Comment by xiaomintongxue** [comment]
@zmrenwu 确实是这样的，我试过了。
因为是新手，还有个问题请教一下，就是url.py中的as_view()是什么意思？能具体讲解下其含义和功能吗？
包括里面导入的ListView和DetailView之类，非常感谢~~~

**Comment by zmrenwu** [comment]
as_view() 的功能是把类转为一个函数。我们通常写的视图函数是一个普通的 python 函数，它被绑定在某个 url 上，这里的 as_view() 就是把类转为同功能的 python 函数，然后绑定在 url 上。
基于类的视图函数请看：http://www.jianshu.com/p/00bf223873b3
