### ISSUE TITLE
workspace.xml是干什么用的？是自动生成的吗？当点击一个add按钮增加一篇文章的时候，是怎么处理这个路径的哦请求的？

### ISSUE THREAD

**Issue by dapsjj** [zmrenwu/django-blog-tutorial#79]
1、workspace.xml是干什么用的？是自动生成的吗？
2、再有就是http://localhost:8000/admin/blog/article/add/
  这种增加一篇文章的这个请求对应的处理文件是啥？也就是这个请求发出的时候是怎么处理的，我并没有看见有对http://localhost:8000/admin/blog/article/add/
这个的处理，在urls.py中没有这个关键字"add",还有就是点击change的时候，是怎么处理这么请求的？点击change的url是：http://localhost:8000/admin/blog/article/

**Comment by zmrenwu** [comment]
workspace.xml 是 pycharm 生成的文件，忘记加入 ignore 了，不必在意。http://localhost:8000/admin/blog/article/add/ 这些都是 django admin 自带的，本质上和我们自己写的视图函数和 url 是一样的。比如 http://localhost:8000/admin/blog/article/add/ 对应一个添加文章的视图函数。
