### ISSUE TITLE
建议修改分支至tag

### ISSUE THREAD

**Issue by liangliangyy** [zmrenwu/django-blog-tutorial#83]
使用tag来区分不同版本岂不是更好?
而且分支名这么长....还有特殊字符...
使用tag的话更容易处理版本等.

**Comment by zmrenwu** [comment]
因为分支代码也可能更新，如果使用 tag 的话我担心无法更新代码。不知道 tag 能否满足需求？

**Comment by liangliangyy** [comment]
了解 可以更新的 只是有点麻烦,.这个issue我关掉了~~
