### ISSUE TITLE
13 评论出错，无法解决，请查看

### ISSUE THREAD

**Issue by gistmap** [zmrenwu/django-blog-tutorial#84]
我对了3遍，还是没有解决。
**报错信息：**
blogproject\blog\urls.py line 2 
from . import views
blogproject\blog\views line 2
from comments.forms import CommentForm
ImportError: No module named 'comments.forms'

**Comment by zmrenwu** [comment]
No module named 'comments.forms'，你没有在 blog app 下创建 forms.py 模块。

**Comment by gistmap** [comment]
![image](https://cloud.githubusercontent.com/assets/10154728/25114606/5a6f1d3e-2432-11e7-9196-a34df9c10528.png)
我创建了呢

**Comment by zmrenwu** [comment]
我搞错了，不好意思，是在 comments app 下创建 forms.py
