### ISSUE TITLE
这大概是我看到的最完整详细的django教程了，给赞一个

### ISSUE THREAD

**Issue by Superb-x** [zmrenwu/django-blog-tutorial#89]

**Comment by Superb-x** [comment]
博主，我是个前端程序员，大学的时候学过C/C++,去年开始接触Python，一直想自己动手搭博客，开始的时候拿了Django的文档就开始啃，英语水平差了点，有些复杂的地方理解不了，看到你的博客，发现实在是太赞了，有兴趣跟你一起写教程，如有需要，很乐意帮忙做点前端的东西。

**Comment by zmrenwu** [comment]
热烈欢迎！加我微信 zmrenwu 聊聊想法吧。 @Superb-x
