### ISSUE TITLE
缺admin下的静态文件

### ISSUE THREAD

**Issue by canula77** [zmrenwu/django-blog-tutorial#94]
打包您的代码，但是没有admin下的静态文件，请问能被上去吗？谢谢！

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by Bubbleinpit** [comment]
admin下的静态文件，只要在项目的settings.py里写好STATIC_ROOT，然后使用命令
`python manage.py collectstatic`
收集静态文件就可以了。因为admin是Django自带的，这个本来就有。

博主的这篇文章里详细讲过[https://www.zmrenwu.com/post/20/](url)
